IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'$DBNAME$')
	DROP DATABASE [$DBNAME$]
GO
/*
CREATE DATABASE [$DBNAME$]  ON (NAME = N'PylonV3', FILENAME = N'$DBPATH$\PylonV3.MDF' , SIZE = 6, FILEGROWTH = 10%) LOG ON (NAME = N'PylonV3_Log', FILENAME = N'$DBPATH$\PylonV3_Log.LDF' , SIZE = 1, FILEGROWTH = 10%)
	COLLATE Korean_Wansung_CI_AS
GO
*/


CREATE DATABASE PYLONV3
	COLLATE Korean_Wansung_CI_AS
GO

/*  Ab SQL Server 2012 existiert sp_dboption not available! */
/* ALTER DATABASE [$DBNAME$] */
ALTER DATABASE PYLONV3
 SET AUTO_CLOSE OFF,
  RECOVERY SIMPLE,
	TORN_PAGE_DETECTION ON,
	READ_WRITE,
	MULTI_USER,
	AUTO_SHRINK ON,
	ANSI_NULL_DEFAULT OFF,
	RECURSIVE_TRIGGERS OFF,
	ANSI_NULLS OFF,
	CONCAT_NULL_YIELDS_NULL OFF,
	CURSOR_CLOSE_ON_COMMIT OFF,
	CURSOR_DEFAULT GLOBAL,
	QUOTED_IDENTIFIER OFF,
	ANSI_WARNINGS OFF,
	AUTO_CREATE_STATISTICS ON,
	AUTO_UPDATE_STATISTICS ON
GO
